---
title: "Day 3 R"
author: "Marcus Thuillier"
date: "9/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
generation <- read.csv(here::here("data/generation.csv"), 
                       stringsAsFactors = F)
imports <- read.csv(here::here("data/imports.csv"), 
                    stringsAsFactors = F)
```

```{r}
str(generation)
str(imports)
```

```{r}
class(generation$datetime)
class(imports$datetime)
```

```{r}
library(lubridate)
generation$datetime <- as_datetime(generation$datetime)
class(generation$datetime)
head(generation$datetime)
```

```{r}
imports$datetime <- as_datetime(imports$datetime)
class(imports$datetime)
head(imports$datetime)
```

```{r}
head(generation)
```

```{r}
library(reshape2)
long_gen <- melt(generation, id.vars = "datetime",
                           variable.name = "source",
                           value.name = "usage")
head(long_gen)
```

```{r}
long_gen[order(long_gen$datetime)[1:20], ]
```

```{r}
merged_energy <- merge(generation, imports, by = "datetime")
```

```{r}
long_merged_energy <- melt(merged_energy, id.vars = "datetime",
                           variable.name = "source",
                           value.name = "usage")
head(long_merged_energy)
```

```{r}
library(dplyr)
tmp <- select(merged_energy, biogas, biomass, geothermal, solar)
names(tmp)
tmp <- select(merged_energy, -biogas, -biomass, -geothermal, -solar)
names(tmp)
```

```{r}
tmp <- filter(merged_energy, imports > 7000)
nrow(tmp)
head(tmp)
```

```{r}
tmp <- mutate(long_merged_energy, log_usage = log(usage))
head(tmp)
```

```{r}
# total energy consumption
summarize(long_merged_energy, total = sum(usage, na.rm = T))

# mean energy consumption
summarize(long_merged_energy, mean_cons = mean(usage, na.rm = T))
```

```{r}
long_merged_energy %>% 
  filter(source == "geothermal") %>% 
  select(-datetime) %>% 
  mutate(log_usage = log(usage)) %>% 
  summarize(mean_log_usage = mean(log_usage, na.rm = T))
```

```{r}
merged_energy %>% 
  select(-datetime) %>% 
  mutate(total_usage = rowSums(., na.rm = T)) %>% 
  summarize(total_usage = sum(total_usage, na.rm = T))
```

```{r}
merged_energy %>%
  select(contains("hydro")) %>%
  mutate(total_hydro = rowSums(., na.rm = T)) %>%
  summarize(mean_hydro = mean(total_hydro, na.rm = T))
```

```{r}
gapminder <- read.csv(here::here("data/gapminder5.csv"))

gapminder %>% 
  group_by(year) %>% 
  summarize(mean_le = mean(lifeExp, na.rm = T),
            sd_lf = sd(lifeExp, na.rm = T))
```

```{r}
merged_energy %>%
  select(datetime, contains("hydro"), starts_with("bio")) %>%
  melt(id.vars = "datetime",
       variable.name = "source",
       value.name = "usage") %>%
  group_by(source) %>% 
  summarize(mean_usage = mean(usage, na.rm = T))

```








































































